### ISSUE TITLE
New version of gem needed

### ISSUE THREAD

**Issue by ukd1** [jackruss/faker-medical#5]
We've just added this to our project and get some development dependancies mixed in incorrectly, however master doesn't. Could you re-publish a newer version of this gem to fix this?

![screenshot 2014-05-13 11 16 38](https://cloud.githubusercontent.com/assets/44345/2961849/c3374e7c-daca-11e3-84dd-e87b139e513c.png)

Also, it seems like the method names are different in the published version vs master. This breaks anything using the older version (as I just found out). Let me know when you publish the newer one, I'm happy to fix the docs again.

Russ

**Comment by rdniller** [comment]
@ukd1 -  Russ, gem is republished with newer version [0.5.1](https://rubygems.org/gems/faker-medical).  Thanks for your help.

Russell

**Comment by ukd1** [comment]
:+1:

**Comment by jackhq** [comment]
Cool

Thx

Tom

Sent from my iPhone

On May 13, 2014, at 4:54 PM, rdniller notifications@github.com wrote:

@ukd1 https://github.com/ukd1 - Russ, gem is republished with newer
version 0.5.1 https://rubygems.org/gems/faker-medical. Thanks for your
help.

Russell

—
Reply to this email directly or view it on
GitHubhttps://github.com/jackhq/faker-medical/issues/5#issuecomment-43011315
.
